FROM python:3.12-slim

WORKDIR /app

COPY ip_updater.py requirements.txt ./

RUN pip install -r requirements.txt

# Environment variables
ENV IP_FILE=/app/allowed_ips.json
ENV AWS_REGION=eu-west-1

CMD ["python", "ip_updater.py"]
