apiVersion: apps/v1
kind: Deployment
metadata:
  name: access-verifier
  labels:
    app: access-verifier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: access-verifier
  template:
    metadata:
      labels:
        app: access-verifier
    spec:
      containers:
      - name: access-verifier
        image: your-access-verifier-image:latest
        ports:
        - containerPort: 5000
        env:
        - name: IP_FILE
          value: "/app/allowed_ips.json"
        - name: FORWARDED_HEADER
          value: "X-Forwarded-For"
        volumeMounts:
        - mountPath: /app
          name: ip-volume
      volumes:
      - name: ip-volume
        persistentVolumeClaim:
          claimName: ip-volume-claim
