apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-allowed-ips
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ip-updater
            image: access-verifier:latest
            command: ["python", "ip_updater.py"]
          restartPolicy: OnFailure
