apiVersion: v1
kind: PersistentVolume
metadata:
  name: ip-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce  
  hostPath:          
    path: "/data/allowed_ips"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ip-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
